[package]
name = "webdav-server"

# When releasing to crates.io:
# - Update html_root_url in src/main.rs
# - Update CHANGELOG.md.
# - Create git tag webdav-server-0.x.y
version = "0.4.2"

description = "webdav/http server with support for user accounts"
readme = "README.md"
documentation = "https://docs.rs/webdav-server"
repository = "https://github.com/miquels/webdav-server-rs"
homepage = "https://github.com/miquels/webdav-server-rs"
authors = ["Miquel van Smoorenburg <mike@langeraar.net>"]
edition = "2021"
license = "Apache-2.0"
categories = ["filesystem"]

[workspace]
members = [
    ".",
    "fs_quota",
    "pam",
]

[features]
# By default, the "pam" and "quota" features are enabled.
#
# Some systems do not have pam (like OpenBSD), so to compile this
# package without pam but with quota use:
#
#     cargo build --release --no-default-features --features=quota
#
default = [ "pam", "quota" ]

# dependencies for the feature.
pam = [ "pam-sandboxed" ]
quota = [ "fs-quota" ]

# Include debug info in release builds.
[profile.release]
debug = true

# Build dependencies in optimized mode, even for debug builds.
[profile.dev.package."*"]
opt-level = 3

# Build dev-dependencies in non-optimized mode, even for release builds.
[profile.dev.build-override]
opt-level = 0

[dependencies]
bytes = "1"
clap = { version = "4.5", features = ["derive", "env"] }
dav-server = { version = "0.11", features = ["localfs"] }
env_logger = "0.11"
fs-quota = { path = "fs_quota", version = "0.1.0", optional = true }
futures = "0.3"
futures-util = "0.3"
headers = "0.4"
http = "1"
http-body-util = "0.1"
hyper = { version = "1.5", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
libc = "0.2"
log = "0.4"
nix = { version = "0.29", features = ["process", "user", "fs", "signal"] }
pam-sandboxed = { path = "pam", version = "0.2.0", optional = true }
percent-encoding = "2.3"
pwhash = "1.0.0"
regex = "1.11"
rustls-pemfile = "2.2"
serde = { version = "1.0", features = ["derive"] }
socket2 = { version = "0.5", features = ["all"] }
tls-listener = { version = "0.10", features = ["rustls"] }
tokio = { version = "1.40", features = ["full"] }
tokio-rustls = "0.26"
toml = "0.8"
url = "2.5"
